title: Kongsi Ilmu ICT
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://megatazm.github.io" # the base hostname & protocol for your site, e.g. https//megatazm.github.io
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Dr. Megat Azmi # add your name
author-img: megat-azmi.jpg # add your photo
about-author: Saya seorang pensyarah biasa yang berminat untuk berkongsi ilmu ICT dalam Bahasa Malaysia dengan harapan dapat menyemai perasaan minat di kalangan anak-anak muda. # add description
social-twitter: "megatazm" # add your Twitter handle
social-facebook: "groups/264524460634420/"# add your Facebook handle
social-github: "megatazm" # add your Github handle
social-linkedin: "megat-azmi-903550166/"# add your Linkedin handle
social-email: "megatnorulazmi@gmail.com" # add your Email address

# Disqus
discus-identifier: Megat Azmi # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
